# Generated by Django 3.0.4 on 2020-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.CharField(max_length=100, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=20, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='phone number'),
        ),
    ]
