# Generated by Django 3.0.4 on 2020-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200505_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_bookmarks',
            field=models.CharField(max_length=1000000, null=True, verbose_name='my_applications'),
        ),
    ]
