# Generated by Django 3.0.4 on 2020-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200506_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_accepted',
            field=models.CharField(default='~', max_length=1000000, null=True, verbose_name='my_Accepted'),
        ),
    ]
