# Generated by Django 3.0.4 on 2020-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_my_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.CharField(max_length=100, null=True, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_accepted',
            field=models.CharField(default='%next%', max_length=100000, null=True, verbose_name='my_Accepted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_applications',
            field=models.CharField(default='%next%', max_length=100000, null=True, verbose_name='my_Applications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_bookmarks',
            field=models.CharField(default='%next%', max_length=100000, null=True, verbose_name='my_Bookmarks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.CharField(max_length=100, null=True, verbose_name='skype name'),
        ),
    ]
