# Generated by Django 3.0.4 on 2020-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200508_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.CharField(blank=True, default='Not availabe', max_length=100, null=True, verbose_name='skype name'),
        ),
    ]
