# Generated by Django 3.0.4 on 2020-05-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_auto_20200505_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='title',
            new_name='name',
        ),
    ]
