# Generated by Django 3.0.4 on 2020-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_auto_20200505_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='comma_seperated_names_of_selected_students',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
