# Generated by Django 3.0.4 on 2020-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_internships_comma_seperated_names_of_selected_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internships',
            name='university',
        ),
        migrations.AddField(
            model_name='internships',
            name='University',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
