# Generated by Django 3.0.4 on 2020-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_auto_20200505_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
