# Generated by Django 3.0.4 on 2020-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_auto_20200505_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='deadline',
            field=models.DateField(),
        ),
    ]
