# Generated by Django 3.0.4 on 2020-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_auto_20200506_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='contact_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
