# Generated by Django 3.0.4 on 2020-05-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0011_internships_contact_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internships',
            old_name='contact_details',
            new_name='contact_email',
        ),
    ]
