# Generated by Django 3.0.4 on 2020-05-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_auto_20200506_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internships',
            old_name='comma_seperated_names_of_selected_students',
            new_name='comma_seperated_emails_of_selected_students',
        ),
    ]
