# Generated by Django 3.0.4 on 2020-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0015_auto_20200507_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='one_contact_email',
            field=models.CharField(max_length=500),
        ),
    ]
