# Generated by Django 3.0.4 on 2020-05-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_auto_20200507_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
