# Generated by Django 3.0.4 on 2020-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_auto_20200507_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Title (will be treated as new internship if you edit again)'),
        ),
    ]
