# Generated by Django 3.0.4 on 2020-05-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0020_auto_20200509_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Title of the Internship __(will be treated as new internship if you edit again)'),
        ),
    ]
